### ISSUE TITLE
Wont compile.

### ISSUE THREAD

**Issue by DCooper-nz** [CelliesProjects/wm8978-esp32#2]
I haven't been able to get the code to compile, I get these errors:
WM8978.cpp:321:18: error: could not convert 'Wire.TwoWire::begin(((int)sda), ((int)scl), ((uint32_t)frequency))' from 'void' to 'bool'
   if (!Wire.begin(sda, scl, frequency)) {
and
WM8978.cpp:321:38: error: in argument to unary !
   if (!Wire.begin(sda, scl, frequency)) {

**Comment by CelliesProjects** [comment]
I am assuming you have an issue with the example code?

My first guess would be that you have a different `Wire` lib installed.

What Arduino IDE, esp32 core version are you using? 

Which `Wire` version are you using?

You can check your `Wire` version by enabling the `compilation` checkbox after `Show verbose output during` in the preferences menu.
Now recompile.
Somewhere at the bottom of the compilation output should now be something like:

`Using library Wire at version 1.0.1 in folder: /home/cellie/Arduino/hardware/espressif/esp32/libraries/Wire `

**Comment by DCooper-nz** [comment]
Apologies for taking so long to reply. It was a library issue on my machine which had become a bit of a mess. I reinstalled all libraries and its compiling fine now. Is it possible to play a file from an sd card on the m5stack, I'm having trouble connecting the m5stack sd card file opening code and the audio library's audio.connecttoFS(); command. Any help would be much appreciated.

**Comment by CelliesProjects** [comment]
Closing this issue as it seems resolved.
