### ISSUE TITLE
High power consumption 

### ISSUE THREAD

**Issue by ceear** [CelliesProjects/wm8978-esp32#7]
Hi,

I am currently testing with a ttgo audio kit (wm8978) and a custom pcb design. 

In both cases I notice a very high power consumption when playing mp3. About 400 mAh and the chip gets very warm. 

Is this normal or am I configuring something wrong?

**Comment by CelliesProjects** [comment]
I only have a M5Stack Node wm8978 with a built-in lithium battery so measuring current consumption is next to impossible.

The [wm8978 specs](http://datasheet.elcodis.com/pdf2/88/68/886842/wm8978.pdf) (p12) mentions a typical use of 71mA.

That 400mA is total system use?

**Comment by ceear** [comment]
system total is about 500 mAh. 100 - 120 when playing mp3 without speaker. after connecting a speaker system total is 500 mAh.

**Comment by CelliesProjects** [comment]
There is your answer.
